# Generated by Django 3.0.8 on 2020-08-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_bidlisting_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidlisting',
            name='active',
        ),
    ]
