# Generated by Django 3.0.8 on 2020-08-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_remove_bidlisting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlisting',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
